name: drenlabs_krala_murnau_portfolio
description: A Flutter application developed for DrenLab, serving a private investigator in Italy. Key features include dynamic card transitions on scrolling, nested scrolling capabilities, and remote location adjustments by the admin

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts:
  carousel_slider:
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Goldman-Bold
      fonts:
        - asset: fonts/Goldman-Bold.ttf
    - family: SansitaSwashed
      fonts:
        - asset: fonts/SansitaSwashed-VariableFont_wght.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf